"""
backend/plant_data.py
======================
Comprehensive botanical and verified medicinal monographs for medicinal plants.
Includes pharmacology, traditional Ayurvedic uses, parts used, safety precautions,
and reliable scientific literature references.
"""

PLANT_DATA = [
    {
        "common_name": "Aloevera",
        "scientific_name": "Aloe barbadensis miller",
        "is_medicinal": True,
        "description": "Aloe vera is a succulent plant species of the genus Aloe. It thrives in arid and tropical climates, storing mucilaginous water gel inside thick, fleshy leaves.",
        "medicinal_uses": ["Topical soothing for first- and second-degree minor burns", "Wound healing and epithelial tissue repair", "Skin hydration and reduction of erythema"],
        "traditional_uses": ["Ayurvedic Kumari formulations for liver and menstrual health", "Soothing digestive acid imbalance", "Hair conditioning and scalp soothing"],
        "parts_used": ["Leaf gel (inner parenchymal pulp)", "Leaf latex"],
        "precautions": ["Oral ingestion of yellow aloe latex contains anthraquinones with strong laxative effects; strictly avoid during pregnancy and lactation.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://nccih.nih.gov/health/aloevera", "https://pubmed.ncbi.nlm.nih.gov/17094824/"]
    },
    {
        "common_name": "Amla",
        "scientific_name": "Phyllanthus emblica",
        "is_medicinal": True,
        "description": "Amla, also known as Indian Gooseberry, is a deciduous tree in the Phyllanthaceae family celebrated for its sour, tannin-rich, vitamin C-dense fruits.",
        "medicinal_uses": ["Potent natural antioxidant and free radical scavenger", "Lipid profile regulation and endothelial support", "Cellular immune response enhancement"],
        "traditional_uses": ["Core ingredient in classical Ayurvedic Chyawanprash and Triphala", "Rasayana (rejuvenator) for vitality and longevity", "Hair follicle nourishment and anti-graying tonic"],
        "parts_used": ["Fruit (fresh and dried pericarp)", "Leaves", "Seeds"],
        "precautions": ["May augment hypoglycemic medications and antiplatelet drugs. Discontinue high therapeutic doses prior to scheduled surgery.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3156450/", "https://pubmed.ncbi.nlm.nih.gov/20506691/"]
    },
    {
        "common_name": "Amruthaballi",
        "scientific_name": "Tinospora cordifolia",
        "is_medicinal": True,
        "description": "Amruthaballi (Giloy or Guduchi) is a climbing deciduous shrub featuring heart-shaped leaves and succulent aerial roots, revered in Ayurveda as the 'herb of immortality'.",
        "medicinal_uses": ["Immunomodulatory macrophage activation", "Antipyretic action against chronic and recurrent fevers", "Hepatoprotective and anti-inflammatory properties"],
        "traditional_uses": ["Classical remedy for chronic fever (Jwara)", "Detoxification of metabolic waste (Ama)", "Supporting glucose metabolism in Prameha"],
        "parts_used": ["Stem (aqueous extract/Satva)", "Leaves", "Roots"],
        "precautions": ["Individuals with autoimmune conditions should use under clinical supervision due to strong immunostimulation.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3644751/", "https://pubmed.ncbi.nlm.nih.gov/22830844/"]
    },
    {
        "common_name": "Arali",
        "scientific_name": "Nerium oleander",
        "is_medicinal": True,
        "description": "Arali (Oleander) is an evergreen ornamental shrub with lanceolate leathery leaves and showy pink, red, or white blossoms. It contains potent cardiac glycosides.",
        "medicinal_uses": ["Investigated under strictly controlled pharmacological settings for cardiotonic and cytotoxic active compounds"],
        "traditional_uses": ["External topical pastes in classical Siddha and folk medicine for stubborn skin lesions and scabies under expert supervision"],
        "parts_used": ["Leaves (external use only)", "Root bark (traditional external)"],
        "precautions": ["HIGHLY TOXIC: All plant parts contain lethal cardiac glycosides (oleandrin). Never ingest internally. Keep away from children and pets.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/books/NBK430888/"]
    },
    {
        "common_name": "Ashoka",
        "scientific_name": "Saraca asoca",
        "is_medicinal": True,
        "description": "Ashoka is a sacred rainforest tree belonging to the Fabaceae family, recognized by fragrant orange-yellow flower clusters and dense pinnate foliage.",
        "medicinal_uses": ["Uterine tonic and astringent for menorrhagia and irregular menstruation", "Antioxidant polyphenols and tannin-mediated tissue tonification", "Analgesic and anti-inflammatory action"],
        "traditional_uses": ["Key ingredient in the classical Ayurvedic formula Ashokarishta", "Alleviating gynecological discomfort and pelvic congestion", "Skin-cooling herbal pastes"],
        "parts_used": ["Stem bark", "Flowers", "Seeds"],
        "precautions": ["Contraindicated during pregnancy due to uterine stimulating activity. Use under certified Ayurvedic supervision.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4649774/"]
    },
    {
        "common_name": "Ashwagandha",
        "scientific_name": "Withania somnifera",
        "is_medicinal": True,
        "description": "Ashwagandha (Indian Ginseng) is an evergreen woody shrub with bell-shaped green flowers and red berries, valued for adaptogenic withanolide glycosides.",
        "medicinal_uses": ["Cortisol regulation and chronic stress alleviation", "Anxiolytic and sleep architecture improvement", "Cognitive endurance and physical stamina enhancement"],
        "traditional_uses": ["Premier Rasayana tonic for deep tissue depletion (Dhatu kshaya)", "Promoting reproductive vitality and vigor", "Joint nourishment"],
        "parts_used": ["Roots", "Leaves"],
        "precautions": ["May increase thyroid hormone production; avoid in hyperthyroidism and during pregnancy. Monitor blood sugar when combined with antidiabetic medications.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://nccih.nih.gov/health/ashwagandha", "https://pubmed.ncbi.nlm.nih.gov/31517876/"]
    },
    {
        "common_name": "Astma_weed",
        "scientific_name": "Euphorbia hirta",
        "is_medicinal": True,
        "description": "Asthma Weed (Euphorbia hirta) is a slender hairy annual herb found across tropical wasteland areas, known for white milky latex and small axillary flower clusters.",
        "medicinal_uses": ["Bronchorelaxant and spasmolytic respiratory support", "Antibacterial action against enteric pathogens", "Antidiarrheal and mild anti-inflammatory properties"],
        "traditional_uses": ["Decoction for asthma, bronchitis, and persistent dry coughs", "Soothing amoebic dysentery and gastrointestinal spasms", "Topical application for wart and skin tag healing"],
        "parts_used": ["Whole herb", "Leaves", "Aerial parts"],
        "precautions": ["Latex is irritating to mucous membranes and eyes. High oral doses cause nausea and gastrointestinal irritation.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3249909/"]
    },
    {
        "common_name": "Balloon_Vine",
        "scientific_name": "Cardiospermum halicacabum",
        "is_medicinal": True,
        "description": "Balloon Vine (Mudakathan) is an herbaceous climbing plant identifiable by inflated papery three-winged capsules and heart-marked black seeds.",
        "medicinal_uses": ["Suppression of inflammatory cytokines (TNF-alpha, IL-6)", "Anti-arthritic and joint pain alleviation", "Antipruritic and dermatological soothing"],
        "traditional_uses": ["Traditional Tamil cuisine herb (Mudakathan Keerai) for joint stiffness and sciatica", "Decoction for rheumatism and lumbago", "Herbal hair oil for dandruff and scalp flaking"],
        "parts_used": ["Leaves", "Aerial shoots", "Roots"],
        "precautions": ["Generally well tolerated in culinary portions. Therapeutic extracts should be avoided during pregnancy.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3655294/"]
    },
    {
        "common_name": "Bamboo",
        "scientific_name": "Bambusa vulgaris",
        "is_medicinal": False,
        "description": "Bamboo is a fast-growing giant perennial grass featuring woody segmented culms, extensively utilized across Asia for construction, handicrafts, and functional foods.",
        "medicinal_uses": ["Extracted bamboo silica (Tabasheer/Banslochan) provides mineral bio-silicon for connective tissue support"],
        "traditional_uses": ["Edible tender shoots (boiled/pickled) in Asian gastronomy", "Bamboo leaf decoction as a cooling astringent tea", "Eco-friendly structural material and crafts"],
        "parts_used": ["Shoots (culinary)", "Leaves", "Tabasheer (siliceous concretion)"],
        "precautions": ["Raw bamboo shoots contain cyanogenic taxiphyllin and must be thoroughly boiled or fermented before ingestion.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://pubmed.ncbi.nlm.nih.gov/21808603/"]
    },
    {
        "common_name": "Betel",
        "scientific_name": "Piper betle",
        "is_medicinal": True,
        "description": "Betel (Paan) is an evergreen dioecious perennial creeper with glossy heart-shaped leaves and catkin flowers, native to Southeast Asia.",
        "medicinal_uses": ["Potent oral antiseptic against Streptococcus mutans and periodontal bacteria", "Digestive carminative and salivary stimulant", "Antioxidant hydroxychavicol content"],
        "traditional_uses": ["Chewed post-meals as an aromatic digestive stimulant (Paan)", "Warm poultice applied to chest for childhood cough relief", "Antiseptic wash for superficial cuts and fungal infections"],
        "parts_used": ["Fresh leaves", "Stems", "Roots"],
        "precautions": ["Avoid chewing betel leaf with areca nut (supari) or tobacco, which is strongly carcinogenic. Pure betel leaf itself is therapeutic.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3892533/"]
    },
    {
        "common_name": "Bhrami",
        "scientific_name": "Bacopa monnieri",
        "is_medicinal": True,
        "description": "Brahmi (Water Hyssop) is a succulent, creeping perennial wetland herb with small oblong leaves and light purple or white solitary flowers.",
        "medicinal_uses": ["Bacoside-mediated memory consolidation and recall speed enhancement", "Neuroprotective free radical neutralization in hippocampus", "Mild anxiolytic and mental clarity promotion"],
        "traditional_uses": ["Classical Medhya Rasayana (mind and intellect rejuvenator)", "Balancing nervous tension and mental restlessness", "Promoting deep restorative sleep and meditation focus"],
        "parts_used": ["Whole herb", "Leaves", "Stalks"],
        "precautions": ["May cause mild nausea, dry mouth, or loose stools when taken on an empty stomach; consume with food or ghee.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3153866/"]
    },
    {
        "common_name": "Bringaraja",
        "scientific_name": "Eclipta prostrata",
        "is_medicinal": True,
        "description": "Bhringraj (False Daisy) is a moisture-loving annual herb with white daisy-like flower heads and lanceolate leaves, revered in Ayurvedic hair and liver formulations.",
        "medicinal_uses": ["Hair follicle stimulation and anagen phase lengthening (wedelolactone)", "Hepatoprotective enzyme regeneration in jaundice and fatty liver", "Antimicrobial and anti-inflammatory action"],
        "traditional_uses": ["Classical 'Keshya' herb for preventing premature hair graying and balding", "Liver tonic formulations in chronic hepatitis", "Calming Pitta-related headaches and skin irritation"],
        "parts_used": ["Whole plant", "Leaves", "Roots"],
        "precautions": ["Safe in standard topical and oral Ayurvedic preparations; excessive doses may feel overly cooling for individuals with cold constitution.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4897414/"]
    },
    {
        "common_name": "Castor",
        "scientific_name": "Ricinus communis",
        "is_medicinal": True,
        "description": "Castor is a fast-growing robust perennial shrub with large palmate leaves and spiny seed capsules containing oil-bearing mottled seeds.",
        "medicinal_uses": ["Topical ricinoleic acid transdermal anti-inflammatory pain relief", "Skin and eyelash emollient hydration", "Pharmacopeia-approved stimulant laxative (purified oil)"],
        "traditional_uses": ["External castor oil warm packs over joints, abdomen, and glands", "Inducing labor under historical obstetrical practice", "Soothing acute constipation"],
        "parts_used": ["Refined seed oil (pure ricin-free oil only)", "Leaves (external warm poultice)"],
        "precautions": ["FATAL POISON: Whole castor seeds contain the lethal ribosome-inactivating protein ricin. Never ingest raw seeds. Castor oil is contraindicated during pregnancy.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6481232/"]
    },
    {
        "common_name": "Catharanthus",
        "scientific_name": "Catharanthus roseus",
        "is_medicinal": True,
        "description": "Catharanthus (Sadabahar / Madagascar Periwinkle) is an evergreen herbaceous shrub featuring glossy oval leaves and 5-lobed pink or white blossoms.",
        "medicinal_uses": ["Source of chemotherapeutic vinca alkaloids (vincristine, vinblastine)", "Hypoglycemic activity via enhanced glucose uptake in peripheral tissues", "Vasodilatory and antihypertensive effects"],
        "traditional_uses": ["Folk remedy for managing diabetes mellitus (decoction of leaves)", "Wasp sting and insect bite soothing paste", "Mild hypotensive tea"],
        "parts_used": ["Leaves", "Roots", "Whole flowering plant"],
        "precautions": ["Vinca alkaloids have high cellular toxicity; medicinal preparations must be medically supervised. Strictly avoid in pregnancy and liver dysfunction.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4562214/"]
    },
    {
        "common_name": "Common_Rue",
        "scientific_name": "Ruta graveolens",
        "is_medicinal": True,
        "description": "Common Rue (Naagdalli) is a strongly scented perennial subshrub with blue-green bipinnate leaves and small yellow flowers, native to the Mediterranean and grown across India.",
        "medicinal_uses": ["Rutin-mediated vascular elasticity and capillary stabilization", "Spasmolytic action on gastrointestinal and bronchial smooth muscle", "Antimicrobial and insect repellent compounds"],
        "traditional_uses": ["Traditional tea for colic, earaches, and infantile abdominal distension", "Warding off insects and scorpions as a domestic botanical barrier", "Joint stiffness liniment"],
        "parts_used": ["Aerial parts", "Leaves"],
        "precautions": ["Contains furanocoumarins that cause severe phytophotodermatitis (skin blisters in sunlight). Highly contraindicated in pregnancy due to abortifacient properties.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://pubmed.ncbi.nlm.nih.gov/26600742/"]
    },
    {
        "common_name": "Coriender",
        "scientific_name": "Coriandrum sativum",
        "is_medicinal": True,
        "description": "Coriander (Dhaniya) is an annual herb belonging to the Apiaceae family, with feathery leaves, umbels of pale pink/white blossoms, and aromatic globular seeds.",
        "medicinal_uses": ["Carminative and digestive enzyme stimulation (linalool content)", "Lipid and blood sugar balancing properties", "Antioxidant and heavy metal chelation support"],
        "traditional_uses": ["Cold infusion of crushed coriander seeds (Dhanyaka Hima) for fever, burning micturition, and internal heat", "Everyday culinary spice and digestive garnishing", "Eye wash in traditional conjunctivitis therapy"],
        "parts_used": ["Leaves (cilantro)", "Seeds (coriander)", "Essential oil"],
        "precautions": ["Safe in all culinary quantities. Rare allergic hypersensitivity may occur in individuals sensitive to Apiaceae family plants.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3931197/"]
    },
    {
        "common_name": "Curry",
        "scientific_name": "Murraya koenigii",
        "is_medicinal": True,
        "description": "The curry tree (Murraya koenigii) is a tropical small tree in the Rutaceae family, renowned for intensely aromatic culinary pinnate leaves.",
        "medicinal_uses": ["Carbazole alkaloid (mahanimbine) anti-hyperglycemic and lipid-lowering activity", "Antioxidant cellular protection against oxidative stress", "Antibacterial efficacy against oral and foodborne pathogens"],
        "traditional_uses": ["Essential culinary seasoning across South Asian cuisine", "Alleviating dysentery, diarrhea, and morning sickness", "Strengthening hair roots and preventing premature greying"],
        "parts_used": ["Leaves", "Bark", "Roots", "Seeds"],
        "precautions": ["Extremely safe in culinary use. Concentrated solvent extracts should be taken under clinical direction.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7069000/"]
    },
    {
        "common_name": "Doddapatre",
        "scientific_name": "Coleus amboinicus",
        "is_medicinal": True,
        "description": "Doddapatre (Indian Borage, Mexican Mint, or Karpooravalli) is a succulent perennial herb with aromatic, thick fleshy velvety leaves smelling reminiscent of oregano and thyme.",
        "medicinal_uses": ["Expectorant and bronchodilator for upper respiratory infections (thymol, carvacrol)", "Antimicrobial against respiratory and oral bacterial strains", "Anti-inflammatory and antipyretic properties"],
        "traditional_uses": ["Classic home remedy for childhood coughs, colds, and sore throats (leaf juice with honey)", "Leaves battered and fried into medicinal pakoras (Doddapatre Bajji) for digestion", "Topical soothing for skin allergies and insect bites"],
        "parts_used": ["Fleshy leaves", "Fresh leaf juice", "Aerial stems"],
        "precautions": ["Very safe in normal culinary and herbal tea quantities. Individuals with known allergies to Lamiaceae should exercise caution.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4960309/"]
    },
    {
        "common_name": "Drumstick",
        "scientific_name": "Moringa oleifera",
        "is_medicinal": True,
        "description": "Moringa (Sahjan / Drumstick) is a drought-resistant tropical tree revered worldwide as a 'miracle tree' due to the extraordinary nutrient density of its leaves, pods, and seeds.",
        "medicinal_uses": ["High-concentration bioavailable micronutrients (Vitamin A, C, iron, calcium, amino acids)", "Blood glucose regulation through isothiocyanate compounds", "Cardiovascular support and serum lipid reduction"],
        "traditional_uses": ["Nutritious green superfood cooked into dals, sambar, and soups", "Post-partum lactation enhancer (galactagogue)", "Water purification using crushed moringa seeds"],
        "parts_used": ["Leaves", "Seed pods (drumsticks)", "Seeds", "Bark"],
        "precautions": ["Moringa bark and root extracts contain alkaloids that can stimulate uterine contractions and should be avoided in pregnancy; leaves and pods are safe.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4490473/"]
    },
    {
        "common_name": "Ekka",
        "scientific_name": "Calotropis gigantea",
        "is_medicinal": True,
        "description": "Ekka (Crown Flower / Madar) is a large xerophytic shrub with broad leathery obovate leaves and waxy lavender or white crown-like blossoms, producing copious milky latex.",
        "medicinal_uses": ["Investigated for cardiotonic calotropin and calactin active compounds", "Anti-arthritic and analgesic action under controlled clinical testing", "Antimicrobial and wound cicatrization properties"],
        "traditional_uses": ["Warmed leaves tied over arthritic joints as a pain-relieving compress", "Sacred offerings to Lord Shiva and Hanuman", "Traditional Siddha purification formulations"],
        "parts_used": ["Warmed leaves (external use only)", "Flowers", "Root bark (expert purification required)"],
        "precautions": ["HIGHLY TOXIC LATEX: Plant sap is caustic and severely damages eye corneas; avoid all contact with eyes and mucous membranes. Internal consumption is dangerous.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4362726/"]
    },
    {
        "common_name": "Eucalyptus",
        "scientific_name": "Eucalyptus globulus",
        "is_medicinal": True,
        "description": "Eucalyptus (Nilgiri) is a tall evergreen tree native to Australia and widely cultivated across South India's Nilgiri hills, featuring aromatic sickle-shaped leaves.",
        "medicinal_uses": ["1,8-cineole (eucalyptol) decongestant and mucolytic activity", "Broad-spectrum antibacterial and antiviral respiratory protection", "Topical counterirritant and arthritic muscle pain relief"],
        "traditional_uses": ["Steam inhalation of fresh leaves or oil for sinusitis, coughs, and nasal congestion", "Nilgiri oil massage for joint ache and rheumatic stiffness", "Antiseptic insect and mosquito repellent"],
        "parts_used": ["Mature leaves", "Steam-distilled essential oil"],
        "precautions": ["Pure eucalyptus essential oil must never be ingested or applied undiluted on the faces of young children or infants due to risk of respiratory spasms.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3600578/"]
    },
    {
        "common_name": "Ganike",
        "scientific_name": "Solanum nigrum",
        "is_medicinal": True,
        "description": "Ganike (Black Nightshade / Makoy / Manathakkali) is an annual herbaceous weed with ovate leaves, small white starry flowers, and clusters of small purple-black ripe berries.",
        "medicinal_uses": ["Hepatoprotective and anti-ulcerogenic gastric lining protection", "Solamargine and steroidal alkaloid free-radical quenching", "Mild diuretic and anti-inflammatory properties"],
        "traditional_uses": ["Leaves cooked as soup or curry (Manathakkali Keerai) for mouth ulcers and stomatitis", "Classical Ayurvedic remedy for hepatic enlargement and spleen disorders", "Soothing chronic gastritis"],
        "parts_used": ["Leaves", "Ripe black berries", "Whole aerial plant"],
        "precautions": ["Unripe green berries contain toxic solanine; consume only mature leaves (cooked) and fully ripe black berries.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3312727/"]
    },
    {
        "common_name": "Ginger",
        "scientific_name": "Zingiber officinale",
        "is_medicinal": True,
        "description": "Ginger (Adrak) is a herbaceous perennial in the Zingiberaceae family, cultivated for aromatic pungent underground rhizomes containing gingerols and shogaols.",
        "medicinal_uses": ["Clinical alleviation of nausea (pregnancy-related, motion sickness, post-operative)", "Cyclooxygenase and lipoxygenase inhibition for joint osteoarthritis pain", "Prokinetic gastrointestinal motility stimulation"],
        "traditional_uses": ["Fresh ginger tea (Adrak Chai) for colds, congestion, and digestive fire (Agni)", "Dry ginger (Shunthi) in classical formulations for respiratory health", "Warm compresses for muscular cramps"],
        "parts_used": ["Fresh and dried rhizomes", "Ginger essential oil"],
        "precautions": ["High therapeutic doses may cause mild heartburn or interact with antiplatelet/anticoagulant drugs. Limit supplemental doses in gallstone conditions.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://nccih.nih.gov/health/ginger", "https://pubmed.ncbi.nlm.nih.gov/30671607/"]
    },
    {
        "common_name": "Guava",
        "scientific_name": "Psidium guajava",
        "is_medicinal": True,
        "description": "Guava (Amrood) is an evergreen tropical shrub/tree known for vitamin C-rich edible fruits and oval, prominently-veined leaves rich in medicinal flavonoids.",
        "medicinal_uses": ["Guava leaf extract exhibits clinical efficacy in acute infectious diarrhea and gastroenteritis", "Antidiabetic inhibition of alpha-glucosidase enzymes", "Oral antimicrobial activity against oral biofilms and gingivitis"],
        "traditional_uses": ["Chewing tender guava leaves for mouth ulcers, bleeding gums, and toothache", "Leaf decoction for resolving watery dysentery", "Nutritious fresh fruit consumption for vitamin C and fiber"],
        "parts_used": ["Tender leaves", "Fruit pulp and peel", "Bark"],
        "precautions": ["Guava leaves are very safe. Excessive unripe fruit intake may cause mild constipation due to high astringent tannins.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5571971/"]
    },
    {
        "common_name": "Henna",
        "scientific_name": "Lawsonia inermis",
        "is_medicinal": True,
        "description": "Henna (Mehendi) is a glabrous branched tall shrub with small opposite elliptical leaves and fragrant creamy blossoms, famed for the dyeing pigment lawsone.",
        "medicinal_uses": ["Broad-spectrum antifungal efficacy against dermatophytes (athlete's foot, tinea)", "Wound healing and topical astringent cooling", "Antimicrobial against Staphylococcal skin infections"],
        "traditional_uses": ["Body art and ceremonial mehendi cooling adornment", "Natural conditioning and coloring agent for hair and scalp", "Cooling soles of feet for burning feet syndrome"],
        "parts_used": ["Dried powdered leaves", "Bark", "Seeds"],
        "precautions": ["Contraindicated in individuals with G6PD deficiency (can trigger acute hemolysis). Avoid adulterated commercial henna containing synthetic p-phenylenediamine (PPD).", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3273913/"]
    },
    {
        "common_name": "Hibiscus",
        "scientific_name": "Hibiscus rosa-sinensis",
        "is_medicinal": True,
        "description": "Hibiscus (Gudhal) is a bushy evergreen shrub with ovate toothed leaves and dramatic large 5-petaled flowers with prominent staminal columns.",
        "medicinal_uses": ["Anthocyanin-mediated cardioprotection and mild blood pressure moderation", "Hair growth stimulation in animal trials", "Antioxidant and anti-glycation properties"],
        "traditional_uses": ["Infusion of red blossoms for conditioning hair and promoting dark color", "Cooling herbal teas and syrups for summer heat", "Menstrual flow regulation in Ayurvedic traditions"],
        "parts_used": ["Flowers", "Leaves", "Roots"],
        "precautions": ["May lower blood pressure and glucose levels; monitor if taking antihypertensive or hypoglycemic medications. Caution during early pregnancy.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://pubmed.ncbi.nlm.nih.gov/20018807/"]
    },
    {
        "common_name": "Honge",
        "scientific_name": "Pongamia pinnata",
        "is_medicinal": True,
        "description": "Honge (Indian Beech / Karanja) is a medium-sized deciduous tree with glossy pinnate leaves, fragrant purple-pink blossoms, and thick woody seed pods.",
        "medicinal_uses": ["Furanoflavonoid (karanjin) antimicrobial and antifungal skin protection", "Wound healing and tissue regeneration promotion", "Anti-inflammatory and anti-rheumatic topical properties"],
        "traditional_uses": ["Karanja oil applied externally for chronic eczema, psoriasis, and scabies", "Twigs used as traditional toothbrushes (datun) for gingival health", "Bio-diesel and organic pest deterrent"],
        "parts_used": ["Seed oil (external use)", "Leaves", "Bark"],
        "precautions": ["Seed oil contains non-edible bitter furanoflavonoids and is intended strictly for external topical use; do not ingest.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3336219/"]
    },
    {
        "common_name": "Insulin",
        "scientific_name": "Chamaecostus cuspidatus",
        "is_medicinal": True,
        "description": "The Insulin Plant (Fiery Costus) is a spiraling perennial herb with smooth dark green leaves and brilliant orange flowers, popular in South India for blood glucose balance.",
        "medicinal_uses": ["Experimental enhancement of peripheral insulin sensitivity and beta-cell support", "Antioxidant protection against diabetic nephropathy and oxidative stress", "Mild hypolipidemic activity"],
        "traditional_uses": ["Chewing 1 to 2 fresh leaves daily in folk complementary management of diabetes", "Ornamental shade-loving garden plant", "Traditional decoctions for metabolic health"],
        "parts_used": ["Fresh leaves", "Rhizomes"],
        "precautions": ["Individuals taking prescribed insulin or oral antidiabetic drugs must monitor blood glucose to avoid unexpected hypoglycemia. Consult physician.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3931203/"]
    },
    {
        "common_name": "Jasmine",
        "scientific_name": "Jasminum officinale",
        "is_medicinal": False,
        "description": "Jasmine is an evergreen or deciduous vine/shrub in the Oleaceae family, cherished throughout history for intense, soothing floral fragrance.",
        "medicinal_uses": ["Essential oil linalool and benzyl acetate exert mild anxiolytic and relaxation effects via olfactory pathways"],
        "traditional_uses": ["Aromatic garlands, hair adornment, and ceremonial temple offerings", "Flavoring green and white tea infusions", "Cosmetic perfumery and aromatherapy"],
        "parts_used": ["Flowers", "Essential oil"],
        "precautions": ["Certain toxic non-Jasminum plants (e.g. Yellow Jessamine / Gelsemium) share common names; ensure proper botanical distinction.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://pubmed.ncbi.nlm.nih.gov/20824050/"]
    },
    {
        "common_name": "Lantana",
        "scientific_name": "Lantana camara",
        "is_medicinal": True,
        "description": "Lantana is an invasive perennial woody shrub with aromatic rough oval leaves and multicolour flower clusters. It is widespread in tropical forests.",
        "medicinal_uses": ["Investigated for triterpenoid lantadene antimicrobial, wound-healing, and insecticidal properties"],
        "traditional_uses": ["Folk medicine poultice for cuts, ulcers, and wound healing in remote rural communities", "Natural mosquito and pest deterrent smoke"],
        "parts_used": ["Leaves (external use only under extreme care)"],
        "precautions": ["TOXIC: Foliage and green berries contain triterpenoids (lantadenes) that cause acute cholestasis, hepatotoxicity, and photosensitization. Do not ingest.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3249912/"]
    },
    {
        "common_name": "Lemon",
        "scientific_name": "Citrus limon",
        "is_medicinal": True,
        "description": "Lemon (Nimbu) is an evergreen flowering tree in the Rutaceae family producing yellow ellipsoidal citrus fruits rich in citric acid and vitamin C.",
        "medicinal_uses": ["Immune support via ascorbic acid and citrus bioflavonoids", "Citrate-mediated prevention of calcium oxalate nephrolithiasis (kidney stones)", "Antimicrobial peel essential oils (limonene)"],
        "traditional_uses": ["Lemon water with honey for weight management and hydration", "Astringent gargle for sore throats", "Culinary seasoning and food preservation"],
        "parts_used": ["Fruit juice", "Fruit peel / zest", "Leaves"],
        "precautions": ["Frequent undiluted lemon juice consumption can erode tooth enamel. Drink diluted and rinse mouth with water afterwards.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4287320/"]
    },
    {
        "common_name": "Lemongrass",
        "scientific_name": "Cymbopogon citratus",
        "is_medicinal": True,
        "description": "Lemongrass is a tall clumping tropical perennial grass with coarse linear leaves that exude an invigorating crisp lemon scent when crushed.",
        "medicinal_uses": ["Citral-rich antimicrobial and antifungal activity", "Anti-inflammatory and analgesic properties via free radical neutralization", "Carminative digestive soothing"],
        "traditional_uses": ["Herbal tea for fever, colds, and flu symptoms", "Culinary aromatic flavoring in Southeast Asian soups and curries", "Aromatherapy for mental focus and mosquito repelling"],
        "parts_used": ["Stalks", "Leaves", "Essential oil"],
        "precautions": ["Avoid therapeutic amounts or concentrated essential oil ingestion during pregnancy. Dilute essential oil before topical use to prevent dermatitis.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3217679/"]
    },
    {
        "common_name": "Malabar_Nut",
        "scientific_name": "Justicia adhatoda",
        "is_medicinal": True,
        "description": "Malabar Nut (Vasaka / Adhatoda) is a large dense evergreen shrub featuring lanceolate leaves and white bilabiate flowers, renowned as a premier Ayurvedic respiratory herb.",
        "medicinal_uses": ["Vasicine alkaloid bronchodilation and mucolytic expectoration", "Relief of bronchial spasms in chronic bronchitis and asthma", "Antimicrobial against respiratory pathogens"],
        "traditional_uses": ["Cornerstone of classical Vasavaleha formulations for chronic cough and asthma", "Leaf juice with honey for soothing blood-tinged sputum and hoarseness", "Soothing sore throat and chest congestion"],
        "parts_used": ["Leaves", "Roots", "Flowers"],
        "precautions": ["Contains oxytocic alkaloids that stimulate uterine contractions; contraindicated during pregnancy except under clinical supervision during active labor.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3655289/"]
    },
    {
        "common_name": "Mango",
        "scientific_name": "Mangifera indica",
        "is_medicinal": True,
        "description": "Mango (Aam) is a colossal tropical canopy tree of the Anacardiaceae family, revered as the 'King of Fruits' in India for delicious fruits and bioactive leaves.",
        "medicinal_uses": ["Mangiferin polyphenol antioxidant, anti-inflammatory, and hepatoprotective properties", "Antidiabetic modulation of glucose transporters in preliminary models", "Astringent tannin content in tender leaves supports oral hygiene"],
        "traditional_uses": ["Chewing tender purple/green leaves to strengthen teeth and bleeding gums", "Mango leaf tea for diabetic metabolic balance and mild hypertension", "Ripe sweet fruits for energy and summer rejuvenation"],
        "parts_used": ["Tender leaves", "Fruit pulp and peel", "Seed kernel", "Bark"],
        "precautions": ["Sap and raw peel contain urushiol-like contact allergens that can induce dermatitis in sensitive individuals.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5414457/"]
    },
    {
        "common_name": "Mint",
        "scientific_name": "Mentha spicata",
        "is_medicinal": True,
        "description": "Mint (Pudina) is an aromatic perennial herb with serrated green leaves and square stems, widely cultivated for culinary freshness and digestive therapeutic virtues.",
        "medicinal_uses": ["Menthol/carvone smooth muscle spasmolytic action for irritable bowel symptoms", "Carminative easing of dyspepsia, gas, and abdominal bloating", "Topical cooling analgesic and counterirritant"],
        "traditional_uses": ["Pudina chutney and fresh mint tea for stimulating sluggish digestion", "Inhaling steam with crushed mint for clearing blocked sinuses and headache", "Alleviating nausea and morning sickness"],
        "parts_used": ["Leaves", "Aerial flowering tops", "Essential oil"],
        "precautions": ["May relax lower esophageal sphincter and aggravate gastroesophageal reflux (GERD) in sensitive individuals.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://nccih.nih.gov/health/peppermintoil"]
    },
    {
        "common_name": "Neem",
        "scientific_name": "Azadirachta indica",
        "is_medicinal": True,
        "description": "Neem (Indian Lilac) is an iconic, resilient evergreen tree native to the Indian subcontinent, reverently called the 'village pharmacy' in Ayurveda.",
        "medicinal_uses": ["Azadirachtin and nimbin broad-spectrum antibacterial and antifungal activity", "Dental plaque reduction and periodontal inflammation control", "Antioxidant and immunomodulatory dermatological support"],
        "traditional_uses": ["Neem leaf bathing water for soothing chickenpox, measles, and skin rashes", "Chewing neem twigs (datun) for sparkling teeth and oral hygiene", "Blood purification (Kaphapitta hara) and natural insect repellent"],
        "parts_used": ["Leaves", "Bark", "Seeds / Neem oil", "Twigs"],
        "precautions": ["Neem seed oil is toxic for internal consumption, especially in children (causes Reye's-like syndrome). Contraindicated in pregnancy and fertility treatments.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4791507/"]
    },
    {
        "common_name": "Nelavembu",
        "scientific_name": "Andrographis paniculata",
        "is_medicinal": True,
        "description": "Nelavembu (Kalmegh / King of Bitters) is an intensely bitter annual herbaceous plant with quadrangular stems and lanceolate leaves, revered in Siddha and Ayurveda.",
        "medicinal_uses": ["Andrographolide-mediated reduction in severity and duration of upper respiratory tract infections", "Hepatoprotective and bile-stimulating actions", "Antipyretic efficacy in dengue, malaria, and viral fevers"],
        "traditional_uses": ["Premier component of Nilavembu Kudineer decoction during viral epidemics", "Restoring sluggish liver function post-jaundice", "Deep metabolic detoxification"],
        "parts_used": ["Aerial parts", "Leaves", "Whole plant"],
        "precautions": ["Very high doses may cause gastric discomfort or allergic skin reactions. Contraindicated during pregnancy due to abortifacient potential.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4032030/"]
    },
    {
        "common_name": "Nerale",
        "scientific_name": "Syzygium cumini",
        "is_medicinal": True,
        "description": "Nerale (Jamun / Black Plum) is a large evergreen tree with smooth grayish-white bark, leathery oblong leaves, and dark purple oblong astringent-sweet berries.",
        "medicinal_uses": ["Jamboline and ellagic acid inhibition of starch-to-sugar conversion in diabetes", "Antioxidant anthocyanins supporting vascular endothelium", "Astringent anti-diarrheal tannins"],
        "traditional_uses": ["Jamun seed powder (Jamun Gutli) for daily blood sugar management in Ayurveda", "Fresh fruit juice for spleen and liver health", "Leaf gargle for spongy bleeding gums and stomatitis"],
        "parts_used": ["Seeds (powdered)", "Fruit pulp", "Bark", "Leaves"],
        "precautions": ["High consumption of seed powder alongside antidiabetic drugs can cause hypoglycemia; monitor glucose levels closely.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3609276/"]
    },
    {
        "common_name": "Nooni",
        "scientific_name": "Morinda citrifolia",
        "is_medicinal": True,
        "description": "Noni (Indian Mulberry) is a small evergreen tropical tree with glossy dark green leaves and distinctive bumpy yellowish-white fruits with a pungent cheese-like aroma.",
        "medicinal_uses": ["Scopoletin and polysaccharide immunomodulation and antioxidant cellular protection", "Analgesic and anti-inflammatory properties", "Cardiovascular support and lipid regulation"],
        "traditional_uses": ["Polynesian and coastal Indian wellness tonic for fatigue and longevity", "Poultice of warmed leaves applied to boils and aching joints", "Skin cleansing fruit wash"],
        "parts_used": ["Ripe fermented fruit juice", "Leaves", "Roots"],
        "precautions": ["Contains significant potassium content; contraindicated in advanced kidney disease or hyperkalemia. Monitor liver enzymes if using high extracts.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5920425/"]
    },
    {
        "common_name": "Papaya",
        "scientific_name": "Carica papaya",
        "is_medicinal": True,
        "description": "Papaya (Papita) is a fast-growing herbaceous tree-like plant with a hollow trunk, large palmately lobed leaves, and large edible melon-like fruits.",
        "medicinal_uses": ["Papaya leaf extract clinically increases thrombocyte (platelet) counts in dengue fever", "Papain enzyme proteolytic digestion of proteins and digestive comfort", "Antioxidant carotenoids (lycopene) supporting cellular health"],
        "traditional_uses": ["Fresh papaya leaf juice given in thrombocytopenia and viral fevers", "Raw papaya cooked into digestive curries and pickles", "Crushed black seeds chewed for intestinal parasites"],
        "parts_used": ["Leaves (crushed extract)", "Ripe fruit", "Unripe green fruit", "Seeds"],
        "precautions": ["Unripe green papaya contains high latex concentrations that stimulate uterine contractions; contraindicated in pregnancy. Ripe papaya is safe.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4228512/"]
    },
    {
        "common_name": "Parijatha",
        "scientific_name": "Nyctanthes arbor-tristis",
        "is_medicinal": True,
        "description": "Parijata (Night-flowering Jasmine / Harsingar) is a terrestrial shrub or small tree with sandpaper-rough leaves and exquisitely fragrant white flowers with orange-red tubular centers that bloom at dusk.",
        "medicinal_uses": ["Potent analgesic and anti-inflammatory efficacy in sciatica, arthritis, and rheumatism", "Antipyretic action against intermittent fevers and malaria", "Antioxidant iridoid glucosides"],
        "traditional_uses": ["Boiling 5-6 fresh leaves into morning decoction for acute sciatica (Gridhrasi) and joint pain", "Flowers used for ceremonial worship and natural saffron-orange dye", "Expectorant cough syrup with honey"],
        "parts_used": ["Rough leaves", "Flowers", "Bark"],
        "precautions": ["Decoction is intensely bitter and potent; adhere strictly to traditional dosages. Consult an Ayurvedic doctor during pregnancy.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3249920/"]
    },
    {
        "common_name": "Pepper",
        "scientific_name": "Piper nigrum",
        "is_medicinal": True,
        "description": "Black Pepper (Kali Mirch) is a woody climbing flowering vine in the Piperaceae family, celebrated globally as the 'King of Spices' for pungent berry peppercorns.",
        "medicinal_uses": ["Piperine bioavailability enhancement of curcumin and other co-administered phytocompounds by up to 2000%", "Stimulation of digestive enzymes and gastric hydrochloric acid secretion", "Antimicrobial and thermogenic properties"],
        "traditional_uses": ["One of the three pillars of classical Ayurvedic Trikatu formula (for Kapha and Agni)", "Chewing whole peppercorns with honey for hoarseness, cough, and throat irritation", "Culinary universal seasoning"],
        "parts_used": ["Dried unripe berries (black pepper)", "Dried ripe berries (white pepper)"],
        "precautions": ["May irritate gastric mucosa in individuals with active peptic ulcers or severe gastritis. Piperine alters prescription drug metabolism.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3918798/"]
    },
    {
        "common_name": "Pomegranate",
        "scientific_name": "Punica granatum",
        "is_medicinal": True,
        "description": "Pomegranate (Anar / Dadima) is a fruit-bearing deciduous shrub renowned for glossy leathery foliage, vivid scarlet flowers, and ruby-jeweled aril seeds.",
        "medicinal_uses": ["Punicalagin and ellagic acid cardiovascular endothelial protection and blood pressure moderation", "Astringent anti-diarrheal and gut mucosal protective tannins in peel", "Antimicrobial against dental pathogens"],
        "traditional_uses": ["Classical Dadimadi formulations in Ayurveda for anemia (Pandu) and digestion", "Decoction of dried rind for stubborn amoebic dysentery", "Nutritious blood-building fruit consumption"],
        "parts_used": ["Fruit arils/juice", "Dried fruit rind / peel", "Flowers", "Seeds"],
        "precautions": ["Pomegranate rind is intensely astringent; consume only in measured doses. May mildly interact with ACE inhibitors or statins.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4007340/"]
    },
    {
        "common_name": "Rose",
        "scientific_name": "Rosa damascena",
        "is_medicinal": True,
        "description": "Rose (Gulab) is a woody perennial flowering shrub renowned across civilizations for magnificent fragrant blossoms and cooling petals.",
        "medicinal_uses": ["Antimicrobial and mild anti-inflammatory ophthalmic and skin soothing", "Aromatherapy reduction in stress hormones and nervous tension", "Mild laxative and gut cooling properties"],
        "traditional_uses": ["Classical Ayurvedic Gulkand (sun-cooked rose petal preserve) for internal Pitta heat, acidity, and fatigue", "Pure rose water (Gulab Jal) eye drops for tired burning eyes", "Cardiotonic calming sherbets"],
        "parts_used": ["Petals", "Rose water distillate", "Rose hips", "Essential oil (Rose Otto)"],
        "precautions": ["Ensure culinary or therapeutic roses are organic and free of commercial florist pesticides.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3586833/"]
    },
    {
        "common_name": "Tamarind",
        "scientific_name": "Tamarindus indica",
        "is_medicinal": True,
        "description": "Tamarind (Imli) is a majestic long-lived tropical tree with feathery pinnate foliage and cinnamon-brown curved legume pods holding tart, sticky pulp.",
        "medicinal_uses": ["Tartaric acid, malic acid, and potassium provide gentle osmotic laxative effects", "Antioxidant polyphenols in seed coat and pulp support lipid metabolism", "Fluoride excretion facilitation in fluorosis models"],
        "traditional_uses": ["Culinary acidulant in rasam, sambar, chutneys, and curries across South Asia", "Cooling tamarind sherbet for heatstroke recovery", "Bark and leaf poultices applied to swollen sprains"],
        "parts_used": ["Fruit pulp", "Seeds", "Leaves", "Bark"],
        "precautions": ["Excessive consumption may cause tooth enamel sensitivity due to natural fruit acids; rinse mouth after sour drinks.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3210008/"]
    },
    {
        "common_name": "Thumbe",
        "scientific_name": "Leucas aspera",
        "is_medicinal": True,
        "description": "Thumbe (Dronapushpi) is an erect, aromatic annual herb with quadrangular stems, linear leaves, and distinctive whorls of velvety white tubular flowers.",
        "medicinal_uses": ["Antipyretic and analgesic action in traditional fever management", "Antimicrobial against respiratory and cutaneous pathogens", "Antihistaminic and mast-cell stabilization properties"],
        "traditional_uses": ["Instilling 1-2 drops of purified leaf juice into nostrils (Nasya) in traditional sinus headaches and jaundice", "Flowers offered in sacred worship of Lord Shiva", "Leaf juice applied to insect and snake bites in folklore"],
        "parts_used": ["Whole herb", "Leaves", "White flowers"],
        "precautions": ["Nasya (nasal instillation) must be carried out only by qualified Ayurvedic doctors to avoid nasal irritation.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3249911/"]
    },
    {
        "common_name": "Tulsi",
        "scientific_name": "Ocimum tenuiflorum",
        "is_medicinal": True,
        "description": "Tulsi (Holy Basil) is a sacred, highly aromatic shrub in the mint family Lamiaceae, revered across India as the 'Queen of Herbs' for adaptogenic and restorative power.",
        "medicinal_uses": ["Adaptogen supporting physiological, metabolic, and psychological resilience to stress", "Eugenol and rosmarinic acid antimicrobial and anti-inflammatory properties", "Respiratory tract soothing and bronchodilation"],
        "traditional_uses": ["Daily morning infusion for immunity, vitality, and longevity", "Chewed with black pepper for colds, flu, and respiratory congestion", "Holy water (Charanamrit) preparation in spiritual worship"],
        "parts_used": ["Leaves", "Stems", "Seeds (Sabja/Tulsi seeds)"],
        "precautions": ["May exert mild antiplatelet (blood thinning) and hypoglycemic effects. Exercise caution if taking anticoagulants or antidiabetic drugs.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4296439/", "https://pubmed.ncbi.nlm.nih.gov/24882731/"]
    },
    {
        "common_name": "Turmeric",
        "scientific_name": "Curcuma longa",
        "is_medicinal": True,
        "description": "Turmeric (Haldi) is a rhizomatous perennial plant in the Zingiberaceae family, renowned globally for vivid golden curcuminoids and profound healing virtues.",
        "medicinal_uses": ["Potent antioxidant and NF-kB inflammatory pathway suppression (curcumin)", "Joint comfort, cartilage protection, and arthritis symptom relief", "Endothelial cardiovascular support and metabolic balance"],
        "traditional_uses": ["Topical antiseptic for cuts, burns, wounds, and skin infections", "Golden milk (Haldi Doodh) for coughs, sore throat, and post-illness recovery", "Ubtan herbal beauty paste for clear skin radiance"],
        "parts_used": ["Rhizome (fresh and dried root)", "Leaves"],
        "precautions": ["High supplemental doses may cause digestive upset or increase bleeding risk when taken with anticoagulants. Mild gallbladder stimulation; caution in gallstones.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://nccih.nih.gov/health/turmeric", "https://pubmed.ncbi.nlm.nih.gov/17569207/"]
    },
    {
        "common_name": "camphor",
        "scientific_name": "Cinnamomum camphora",
        "is_medicinal": True,
        "description": "Camphor tree (Kapur) is a large evergreen tree native to East Asia and cultivated across India, with aromatic glossy leaves containing transparent white crystalline camphor.",
        "medicinal_uses": ["Topical counterirritant and cooling local anesthetic for rheumatic joints and chest congestion", "Antipruritic soothing for skin itching and eczema", "Antimicrobial vapor decongestant"],
        "traditional_uses": ["Camphor burning (Aarti) in temple rituals and sacred purification ceremonies", "Dissolved in mustard or coconut oil for chest and joint massage", "Natural moth and insect repellent in fabric storage"],
        "parts_used": ["Steam-distilled wood and leaf crystals (camphor)", "Leaves"],
        "precautions": ["POISONOUS IF INGESTED: Never ingest pure camphor crystals or oil. Ingestion causes seizures and fatal toxicity, especially in children. External use only.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/books/NBK448161/"]
    },
    {
        "common_name": "kamakasturi",
        "scientific_name": "Ocimum basilicum",
        "is_medicinal": True,
        "description": "Kamakasturi (Sweet Basil / Sabja / Maruva) is an annual aromatic herb with ovate leaves, purple-tinted spikes of flowers, and mucilage-coated seeds.",
        "medicinal_uses": ["Sabja seeds provide intense soluble fiber mucilage for cooling digestive heat and easing constipation", "Antioxidant flavonoids (orientin, vicenin) protect cellular DNA", "Antimicrobial essential oils (estragole, linalool)"],
        "traditional_uses": ["Soaked seeds added to cooling summer drinks (Falooda, Sherbet) for instant hydration", "Aromatic sprigs worn in hair and offered in South Indian temples", "Leaves infused for gastric soothing"],
        "parts_used": ["Seeds (Sabja)", "Leaves", "Flowering tops"],
        "precautions": ["Sabja seeds must be thoroughly soaked in water before swallowing to prevent esophageal obstruction due to intense swelling.", "This monograph is for educational purposes only. Consult healthcare professionals before therapeutic use."],
        "sources": ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4264302/"]
    }
]
